# Placeholder for local runs; overwritten by scripts/deploy.sh when deploying remotely.
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor-hub'
    static_configs:
      - targets: ['${PROXY_IP}:8081']

  - job_name: 'cadvisor-clients'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'dcgm-exporters'
    static_configs:
      - targets: ['dcgm-exporter:9400']
