global:
  scrape_interval: 5s
scrape_configs:
- job_name: cadvisor-hub
  static_configs:
  - targets:
    - 10.200.241.101:8081
- job_name: cadvisor-client
  static_configs:
  - targets:
    - 10.200.50.45:8080
    - 82.66.249.165:8080
- job_name: dcgm-exporters
  static_configs:
  - targets:
    - 10.200.50.45:9400
